package erp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DeanScreen1 extends javax.swing.JPanel {
    
    MainWindow mw;
    String id;
    String name;
    String teacher;
    
    
    public void addRows() throws ClassNotFoundException{
        Connection con = null;
        Statement st = null;

        id = newCno.getText();
        name = newCname.getText();
        teacher = newT.getText();
        
        /*
        System.out.println(id);
        System.out.println(name);
        System.out.println(teacher);
        */
        String url = "jdbc:derby:testdb;user=USER12;"; //create=true";
        
        try {
            
            System.setProperty("derby.system.home", 
                    "home/mDbFolder");
            
            //Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            
            DriverManager.registerDriver( new org.apache.derby.jdbc.EmbeddedDriver());
            
            con = DriverManager.getConnection(url);
            st = con.createStatement();
            
            //st.executeUpdate("DROP TABLE USER12.COURSEMASTER");
       
                
            //use when creating for first time
            
            //st.executeUpdate("CREATE TABLE COURSEMASTER(ID VARCHAR(15) PRIMARY KEY,"
            //        + "NAME VARCHAR(30), TEACHER VARCHAR(30))");
            
            st.executeUpdate("INSERT INTO COURSEMASTER VALUES (\'" + id + "\', \'" + name + "\', \'" + teacher + "\')");
            
            
            DriverManager.getConnection("jdbc:derby:;shutdown=true");

        } catch (SQLException ex) {
            
            Logger lgr = Logger.getLogger(DeanScreen1.class.getName());

            if (((ex.getErrorCode() == 50000)
                    && ("XJ015".equals(ex.getSQLState())))) {

                lgr.log(Level.INFO, "Derby shut down normally", ex);

            } else {

                lgr.log(Level.SEVERE, ex.getMessage(), ex);
            }

        } finally {

            try {

                if (st != null) {
                    st.close();
                }
                if (con != null) {
                    con.close();
                }

            } catch (SQLException ex) {
                Logger lgr = Logger.getLogger(DeanScreen1.class.getName());
                lgr.log(Level.WARNING, ex.getMessage(), ex);
            }
        }
    }
    
    
    public DeanScreen1(MainWindow mw) {
        initComponents();
        this.mw = mw;
       
        setSize(this.mw.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        uc_message = new javax.swing.JLabel();
        addTitle = new javax.swing.JLabel();
        Cno = new javax.swing.JLabel();
        newCno = new javax.swing.JTextField();
        Cname = new javax.swing.JLabel();
        newCname = new javax.swing.JTextField();
        t = new javax.swing.JLabel();
        newT = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        titleLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        titleLabel.setText("List of Courses");
        titleLabel.setToolTipText("List of courses to use to create curriculum");

        uc_message.setText("(under construction)");

        addTitle.setText("Add new course:");

        Cno.setText("Course No:");

        newCno.setToolTipText("of format CS290001");
        newCno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCnoActionPerformed(evt);
            }
        });

        Cname.setText("Course Name:");
        Cname.setToolTipText("");

        newCname.setToolTipText("such as Software Engineering Laboratory");
        newCname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCnameActionPerformed(evt);
            }
        });

        t.setText("Teacher:");

        newT.setToolTipText("such as Rajib Mall");
        newT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLabel)
                            .addComponent(uc_message)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addGap(69, 69, 69)
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t)
                                .addGap(18, 18, 18)
                                .addComponent(newT))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cno)
                                .addGap(18, 18, 18)
                                .addComponent(newCno, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newCname)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(uc_message)
                .addGap(29, 29, 29)
                .addComponent(addTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cno)
                    .addComponent(newCno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cname)
                    .addComponent(newCname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t)
                    .addComponent(newT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(nextButton)
                    .addComponent(backButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newCnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCnoActionPerformed
        id = newCno.getText();
    }//GEN-LAST:event_newCnoActionPerformed

    private void newCnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCnameActionPerformed
        name = newCname.getText();
    }//GEN-LAST:event_newCnameActionPerformed

    private void newTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTActionPerformed
        teacher = newT.getText();
    }//GEN-LAST:event_newTActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            addRows();
            newCno.setText("");
            newCname.setText("");
            newT.setText("");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DeanScreen1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        mw.showCard("Dean Screen 2");
        try {
            mw.s3.readAndUpdateCorCodes();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DeanScreen1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        mw.showCard("One");
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cname;
    private javax.swing.JLabel Cno;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addTitle;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField newCname;
    private javax.swing.JTextField newCno;
    private javax.swing.JTextField newT;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel t;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel uc_message;
    // End of variables declaration//GEN-END:variables
}
