
package erp;
public class MainScreen extends javax.swing.JPanel {

    MainWindow mw;
    public MainScreen(MainWindow mw) {
        initComponents();
        this.mw = mw;
        
        setSize(this.mw.getSize());
        
    }

    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        deanScreenButton = new javax.swing.JButton();
        initStuRegButton = new javax.swing.JButton();

        titleLabel.setText("ERP Application");

        deanScreenButton.setText("Dean Controls");
        deanScreenButton.setToolTipText("Add courses and decide semester details");
        deanScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deanScreenButtonActionPerformed(evt);
            }
        });

        initStuRegButton.setText("Initial Student Registration");
        initStuRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initStuRegButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(deanScreenButton)
                        .addGap(35, 35, 35)
                        .addComponent(initStuRegButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(titleLabel)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deanScreenButton)
                    .addComponent(initStuRegButton))
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deanScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deanScreenButtonActionPerformed
        mw.showCard("Dean Screen 1");
    }//GEN-LAST:event_deanScreenButtonActionPerformed

    private void initStuRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initStuRegButtonActionPerformed
        mw.showCard("Init Stud Reg Screen");
    }//GEN-LAST:event_initStuRegButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deanScreenButton;
    private javax.swing.JButton initStuRegButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
