/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package convert;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author chander
 */
public class StudentLogin extends javax.swing.JPanel {
    
    int id;
    JFrame wind;
        
    private void createDb() throws SQLException{
        Connection con = null;
        Statement st = null;
        
        String url = "jdbc:derby:testdb;user=USER12;create=true";
        
        //System.setProperty("derby.system.home", 
        //            "home/mDbFolder");
        DriverManager.registerDriver( new org.apache.derby.jdbc.EmbeddedDriver());
        
        con = DriverManager.getConnection(url);
        st = con.createStatement();
        
        st.executeUpdate("DROP TABLE USER12.STUDENTSLOGIN");
        
        st.executeUpdate("CREATE TABLE STUDENTSLOGIN (ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)," 
                                            + "NAME VARCHAR(25),"
                                            + "ROLL VARCHAR(15)," 
                                            + "MARKS INT"   
                                            + ")");
        
        DriverManager.getConnection("jdbc:derby:;shutdown=true");
        
    }
    
    private void insertDb() throws SQLException{
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        
        String url = "jdbc:derby:testdb;user=USER12;create=true";
        
        //System.setProperty("derby.system.home", 
        //            "home/mDbFolder");
        DriverManager.registerDriver( new org.apache.derby.jdbc.EmbeddedDriver());
        
        con = DriverManager.getConnection(url);
        pst = con.prepareStatement("INSERT INTO STUDENTSLOGIN(NAME, ROLL, MARKS) VALUES(?, ?, ?)",Statement.RETURN_GENERATED_KEYS);
        
        pst.setString(1,nameField.getText());
        pst.setString(2,rollField.getText());
        pst.setInt(3,0);
        
        pst.executeUpdate();
        
        rs = pst.getGeneratedKeys();
        //Statement st = con.createStatement();
        if(rs.next()){
            id = rs.getInt(1);
        }
        
        DriverManager.getConnection("jdbc:derby:;shutdown=true");
 
    }  
    
    public void updateDb(int marks) throws SQLException{
        Connection con = null;
        PreparedStatement pst = null;
        
        String url = "jdbc:derby:testdb;user=USER12;create=true";
        
        //System.setProperty("derby.system.home", 
        //            "home/mDbFolder");
        DriverManager.registerDriver( new org.apache.derby.jdbc.EmbeddedDriver());
        
        con = DriverManager.getConnection(url);
        pst = con.prepareStatement("UPDATE STUDENTSLOGIN SET MARKS = ? WHERE ID = ?");
        
        pst.setInt(1, marks);
        pst.setInt(2, id);
        
        pst.executeUpdate();
        
        DriverManager.getConnection("jdbc:derby:;shutdown=true");
 
    }
    
    
    public StudentLogin(JFrame wind) throws SQLException {
        //createDb();
        this.wind = wind;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rollField = new javax.swing.JTextField();
        startTestButton = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Login");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("Enter Name:");

        nameField.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("Enter Rollno: ");

        rollField.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        rollField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollFieldActionPerformed(evt);
            }
        });

        startTestButton.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        startTestButton.setText("Start Test");
        startTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTestButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(errorMessageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                            .addComponent(startTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                                .addComponent(rollField)))))
                .addGap(35, 35, 35))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(rollField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 56, Short.MAX_VALUE)
                .addComponent(errorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startTestButton))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTestButtonActionPerformed
        if((nameField.getText().equals("") == true)||(rollField.getText().equals("") == true)){
            //errorMessageLabel.setText("It looks like you have entered an invalid input.Try again.");
            JOptionPane.showMessageDialog(this, "It looks like you have entered an invalid input.Try again.");
            return;
        }
        try {
            //update database
            insertDb();
        } catch (SQLException ex) {
            Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        TestPanel t = new TestPanel(this,wind);
        //t.setVisible(true);
        setVisible(false);
        wind.add(t);
        
        //start test using card layout or something such as that
    }//GEN-LAST:event_startTestButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        MainWindow mw = new MainWindow(wind);
        wind.add(mw);
        setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void rollFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField rollField;
    private javax.swing.JButton startTestButton;
    // End of variables declaration//GEN-END:variables
}
